gim/front/dashboard/repositories/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import (AddRepositoryView, RemoveRepositoryView,
                    ChooseRepositoryView, AskFetchAvailableRepositories,
                    ShowRepositoryAjaxView)

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url=reverse_lazy("front:dashboard:home"))),
    url(r'^choose/$', ChooseRepositoryView.as_view(), name='choose'),
    url(r'^add/$', AddRepositoryView.as_view(), name='add'),
    url(r'^remove/$', RemoveRepositoryView.as_view(), name='remove'),
    url(r'^ajax/repo/(?P<name>[^/]+/[^/]+)/$', ShowRepositoryAjaxView.as_view(), name='ajax-repo'),
    url(r'^ask-fetch/$', AskFetchAvailableRepositories.as_view(), name='ask-fetch'),
) + patterns('', *[
    url('^choose/part/%s/' % tab.url_part, tab.as_view(), name='choose-part-%s' % tab.slug) for tab in ChooseRepositoryView.tabs
])

gim/front/dashboard/urls.py
from django.conf.urls import patterns, include, url

from gim.front.activity.urls import activity_pattern

from .views import DashboardHome, DashboardActivityPart

urlpatterns = patterns('',
    url(r'^$', DashboardHome.as_view(), name='home'),
    url(activity_pattern, DashboardActivityPart.as_view(), name='activity'),
    url(r'^repositories/', include('gim.front.dashboard.repositories.urls', namespace='repositories')),
)

gim/front/repository/dashboard/urls.py
from django.conf.urls import patterns, url

from gim.front.activity.urls import activity_pattern

from .views import (DashboardView, MilestonesPart, CountersPart, LabelsPart,
                    LabelsEditor, LabelTypeCreate, LabelTypeEdit,
                    LabelTypePreview, LabelTypeDelete, LabelCreate,
                    LabelEdit, LabelDelete, ActivityPart,
                    MilestoneCreate, MilestoneEdit, MilestoneDelete,
                    HookPart, HookToggle)


urlpatterns = patterns('',
    url(r'^$', DashboardView.as_view(), name=DashboardView.url_name),
    url(r'^milestones/$', MilestonesPart.as_view(), name=MilestonesPart.url_name),
    url(r'^counters/$', CountersPart.as_view(), name=CountersPart.url_name),
    url(r'^labels/$', LabelsPart.as_view(), name=LabelsPart.url_name),
    url(r'^hook/$', HookPart.as_view(), name=HookPart.url_name),
    url(activity_pattern, ActivityPart.as_view(), name=ActivityPart.url_name),

    url(r'^labels/editor/$', LabelsEditor.as_view(), name=LabelsEditor.url_name),
    url(r'^labels/editor/group/create/$', LabelTypeCreate.as_view(), name=LabelTypeCreate.url_name),
    url(r'^labels/editor/group/(?P<label_type_id>\d+)/edit/$', LabelTypeEdit.as_view(), name=LabelTypeEdit.url_name),
    url(r'^labels/editor/group/(?P<label_type_id>\d+)/delete/$', LabelTypeDelete.as_view(), name=LabelTypeDelete.url_name),
    url(r'^labels/editor/group/preview/$', LabelTypePreview.as_view(), name=LabelTypePreview.url_name),
    url(r'^labels/editor/label/create/$', LabelCreate.as_view(), name=LabelCreate.url_name),
    url(r'^labels/editor/label/(?P<label_id>\d+)/edit/$', LabelEdit.as_view(), name=LabelEdit.url_name),
    url(r'^labels/editor/label/(?P<label_id>\d+)/delete/$', LabelDelete.as_view(), name=LabelDelete.url_name),

    url(r'milestone/create/$', MilestoneCreate.as_view(), name=MilestoneCreate.url_name),
    url(r'milestone/(?P<milestone_id>\d+)/edit/$', MilestoneEdit.as_view(), name=MilestoneEdit.url_name),
    url(r'milestone/(?P<milestone_id>\d+)/delete/$', MilestoneDelete.as_view(), name=MilestoneDelete.url_name),

    url(r'hook/toggle/$', HookToggle.as_view(), name=HookToggle.url_name),
)

gim/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('gim.front.urls', namespace='front', app_name='front')),

    url(r'^core-admin/', include(admin.site.urls)),
    url(r'^hooks/', include('gim.hooks.urls', namespace='hooks')),
    url(r'^graphs/', include('gim.graphs.urls', namespace='graphs')),
    url(r'^', include('gim.front.urls', namespace='front', app_name='front')),
)

gim/front/repository/dashboard/forms.py
import json
import re

from django import forms
from django.core import validators

from gim.core.models import (LabelType, LABELTYPE_EDITMODE, Label,
                             GITHUB_STATUS_CHOICES, Milestone, Repository)

from gim.front.widgets import EnclosedInput
from gim.front.mixins.forms import LinkedToRepositoryFormMixin, LinkedToUserFormMixin


class LabelTypeEditForm(LinkedToRepositoryFormMixin):

    format_string = forms.CharField(
                        required=False,
                        label=u'Format',
                        help_text=u'Write the format for labels to match this group, inserting the strings <strong>{label}</strong> for the part to display, and optionnally <strong>{order}</strong> if your labels include a number to order them',
                    )
    format_string_validators = [
        validators.RegexValidator(
            re.compile('\{label\}'),
            'Must contain a "{label}" part',
            'no-label'
        ),
    ]

    labels_list = forms.CharField(
                    required=False,
                    label=u'Labels',
                    help_text=u'Choose which labels to add in this group. You can also add new ones (use a coma to separate them)',
                )

    class Meta:
        model = LabelType
        fields = ('name', 'edit_mode', 'regex', 'format_string', 'labels_list', )
        widgets = {
            'regex': forms.TextInput,
        }

    def __init__(self, *args, **kwargs):

        if kwargs.get('instance') and kwargs['instance'].edit_mode != LABELTYPE_EDITMODE.REGEX and kwargs['instance'].edit_details:
            if 'initial' not in kwargs:
                kwargs['initial'] = {}
            if kwargs['instance'].edit_mode == LABELTYPE_EDITMODE.FORMAT:
                kwargs['initial']['format_string'] = kwargs['instance'].edit_details.get('format_string', '')
            elif kwargs['instance'].edit_mode == LABELTYPE_EDITMODE.LIST:
                kwargs['initial']['labels_list'] = kwargs['instance'].edit_details.get('labels_list', '')

        super(LabelTypeEditForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = 'Choose a name for this group'

        self.fields['regex'].required = False  # will be tested depending on the edit_mode

        self.fields['edit_mode'].widget.attrs['class'] = 'uniform'
        self.fields['edit_mode'].help_text = 'Changing mode don\'t keep your configuration, except when changing to "Regular Expression" (each mode convert its configuration to a regular expression)'

        self.fields['labels_list'].widget.attrs.update({
            'data-labels': self.get_labels_json(),
        })

    def get_labels_json(self):
        data = {l.name: {'name': l.name, 'color': l.color}
                for l in self.repository.labels.all()}
        return json.dumps(data)

    def _clean_fields(self):
        """
        First check the edit_mode then set required flag, and validators, for
        the edit field corresponding to the chosen edit_mode
        """
        self.edit_mode_value = None

        try:
            # get the value of the edit_mode field
            edit_mode_field = self.fields['edit_mode']
            self.edit_mode_value = edit_mode_field.widget.value_from_datadict(
                            self.data, self.files, self.add_prefix('edit_mode'))
            self.edit_mode_value = edit_mode_field.clean(self.edit_mode_value)

            # adapt required attribute and validators of other fields
            if self.edit_mode_value == LABELTYPE_EDITMODE.REGEX:
                self.fields['regex'].required = True

            elif self.edit_mode_value == LABELTYPE_EDITMODE.FORMAT:
                self.fields['format_string'].required = True
                self.fields['format_string'].validators = self.format_string_validators

            elif self.edit_mode_value == LABELTYPE_EDITMODE.LIST:
                self.fields['labels_list'].required = True
        except:
            pass

        # then finally launch the real clean_field process
        super(LabelTypeEditForm, self)._clean_fields()

    def clean(self):
        """
        Create final regex based on input values for other modes
        """
        data = super(LabelTypeEditForm, self).clean()

        if self.edit_mode_value == LABELTYPE_EDITMODE.FORMAT and data.get('format_string'):
            data['regex'] = LabelType.regex_from_format(data['format_string'])

        if self.edit_mode_value == LABELTYPE_EDITMODE.LIST and data.get('labels_list'):
            data['regex'] = LabelType.regex_from_list(data['labels_list'])

        return data

    def save(self, *args, **kwargs):
        """
        Reset the edit_details json field that keep edit
        """
        self.instance.edit_details = {}

        if self.instance.edit_mode == LABELTYPE_EDITMODE.FORMAT:
            self.instance.edit_details = {'format_string': self.cleaned_data['format_string']}

        elif self.instance.edit_mode == LABELTYPE_EDITMODE.LIST:
            labels = ','.join(sorted(self.cleaned_data['labels_list'].split(','), key=unicode.lower))
            self.instance.edit_details = {'labels_list': labels}

        return super(LabelTypeEditForm, self).save(*args, **kwargs)


class LabelTypePreviewForm(LabelTypeEditForm):
    def clean(self):
        # do not do any unicity check
        cleaned_data = super(LabelTypePreviewForm, self).clean()
        self._validate_unique = False
        return cleaned_data


class LabelEditForm(LinkedToRepositoryFormMixin):
    color_validator = validators.RegexValidator(
            re.compile('^[0-9a-f]{6}$', flags=re.IGNORECASE),
            'Must be a valid hex color (without the #)',
            'invalid-color'
        )
    label_name_validator = validators.RegexValidator(
            re.compile('^[^\,]+$'),
            'Must not contain a comma (",")',
            'comma-refused'
        )

    class Meta:
        model = Label
        fields = ('name', 'color', )

    def __init__(self, *args, **kwargs):
        super(LabelEditForm, self).__init__(*args, **kwargs)

        if 'name' in self.fields:
            self.fields['name'].validators = [self.label_name_validator]
        self.fields['color'].validators = [self.color_validator]

    def save(self, commit=True):
        """
        Set the github status
        """
        if self.instance.pk:
            self.instance.github_status = GITHUB_STATUS_CHOICES.WAITING_UPDATE
        else:
            self.instance.github_status = GITHUB_STATUS_CHOICES.WAITING_CREATE
        return super(LabelEditForm, self).save(commit)


class TypedLabelEditForm(LabelEditForm):
    class Meta(LabelEditForm.Meta):
        fields = ('label_type', 'order', 'typed_name', 'color', 'name')

    def __init__(self, *args, **kwargs):
        super(TypedLabelEditForm, self).__init__(*args, **kwargs)
        self.fields['typed_name'].validators = [self.label_name_validator]

    def clean_label_type(self):
        label_type = self.cleaned_data.get('label_type')
        if (
                not label_type
                or
                label_type.repository_id != self.repository.id
                or self.instance and label_type.id != self.instance.label_type_id
            ):
            raise forms.ValidationError('Impossible to save this label')
        return label_type

    def clean(self):
        cleaned_data = super(TypedLabelEditForm, self).clean()

        label_type = cleaned_data.get('label_type')

        if label_type:  # if not, we are in error mode
            if label_type.edit_mode == LABELTYPE_EDITMODE.REGEX:
                raise forms.ValidationError('You cannot add a label directly to a "regex" group')

            if label_type.edit_mode == LABELTYPE_EDITMODE.FORMAT:
                # try to get the full label name, will raise ValidationError if problem
                cleaned_data['name'] = label_type.create_from_format(
                    cleaned_data['typed_name'],
                    cleaned_data.get('order')
                )

            else:  # label_type.edit_mode == LABELTYPE_EDITMODE.LIST:
                cleaned_data['name'] = cleaned_data['typed_name']
                # remember the name if changed to remove it from the list
                if self.instance and self.instance.name != cleaned_data['name']:
                    self._old_label_name = self.instance.name

        return cleaned_data

    def save(self, commit=True):
        label = super(TypedLabelEditForm, self).save(commit=commit)

        # manage the list of labels if we have this kind of label-type
        label_type = self.cleaned_data['label_type']
        if label_type.edit_mode == LABELTYPE_EDITMODE.LIST:
            labels_list = label_type.edit_details['labels_list'].split(u',')
            type_updated = False

            # if the label changed its name, we remove the old one from the list
            if hasattr(self, '_old_label_name') and self._old_label_name in labels_list:
                labels_list.remove(self._old_label_name)
                type_updated = True

            # if the label is new in the type list, add it
            if label.name not in labels_list:
                labels_list.append(label.name)
                type_updated = True

            if type_updated:
                label_type.edit_details['labels_list'] = u','.join(labels_list)
                label_type.regex = label_type.regex_from_list(labels_list)
                label_type.save()

        return label


class DueOnWidget(EnclosedInput, forms.DateInput):
    def __init__(self, attrs=None):
        if not attrs:
            attrs = {}
        if 'placeholder' not in attrs:
            attrs['placeholder'] = 'yyyy-mm-dd'
        if 'maxlength' not in attrs:
            attrs['maxlength'] = 10
        super(DueOnWidget, self).__init__(
            attrs=attrs,
            input_type='text',
            prepend='icon-th',

gim/front/dashboard/views.py
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy

from gim.activity.limpyd_models import RepositoryActivity

from gim.front.mixins.views import WithSubscribedRepositoriesViewMixin, DeferrableViewPart
from gim.front.activity.views import ActivityViewMixin


class DashboardActivityPart(ActivityViewMixin, DeferrableViewPart, WithSubscribedRepositoriesViewMixin, TemplateView):
    part_url = reverse_lazy('front:dashboard:activity')
    template_name = 'front//dashboard/include_activity.html'
    deferred_template_name = 'front/dashboard/include_activity_deferred.html'

    repository_pks = None

    def inherit_from_view(self, view):
        super(DashboardActivityPart, self).inherit_from_view(view)
        self.repository_pks = view.repository_pks

    def get_pks(self):
        return [s.repository_id for s in self.subscriptions]

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardActivityPart, self).get_context_data(**kwargs)

        activity, has_more = RepositoryActivity.get_for_repositories(
                                    pks=self.repository_pks or self.get_pks(),
                                    **self.activity_args
                                )
        context.update({
            'activity': RepositoryActivity.load_objects(activity),
            'more_activity': has_more,
            'activity_mode': 'repositories',
        })

        return context


class DashboardHome(WithSubscribedRepositoriesViewMixin, TemplateView):
    template_name = 'front/dashboard/home.html'
    url_name = 'front:dashboard:home'

    def get_context_data(self, **kwargs):
        context = super(DashboardHome, self).get_context_data(**kwargs)

        repositories = context['subscribed_repositories']
        subscription_by_repo_id = dict((s.repository_id, s) for s in self.subscriptions)

        for repository in repositories:
            repository.user_counts_open = repository.counters.get_user_counts(self.request.user.pk)

        context['subscription_by_repo_id'] = subscription_by_repo_id

        self.repository_pks = subscription_by_repo_id.keys()
        context['parts'] = {
            'activity': DashboardActivityPart().get_as_deferred(self),
        }

        return context

gim/front/repository/dashboard/templates/front/repository/dashboard/labels-editor/base.html
{% extends "front/repository/dashboard/base.html" %}
{% load staticfiles jsonify %}

{% block extra_css %}
    {{ block.super }}
    <link href="{% static "front/css/select.2.css" %}" rel="stylesheet">
    <link href="{% static "front/css/spectrum.css" %}" rel="stylesheet">
    <link href="{% static "front/css/pages/repository/dashboard-editor.css" %}" rel="stylesheet">
{% endblock extra_css %}

{% block body_id %}labels-editor{% endblock %}

{% block dashboard-subtitle %}<h5>Labels and groups editor</h5>{% endblock %}

{% block dashboard-content %}
<div class="row-fluid">
    <div class="box span3">
        <div class="box-header">
            <span class="title">About groups</span>
        </div>
        <div class="box-content padded">
            <p><strong>What is a group ?</strong></p>
            <p>Groups are a way to organize your labels into logical sets.</p>
            <p>When you create a group, you can choose which labels to include by picking them, or by using a pattern.</p>
            <p><strong>An example</strong></p>
            <p>For example, the pattern <strong>workflow:{order}:{label}</strong> will automatically include labels like these:</p>
            {# ul>li({workflow:$:}+strong)*5 #}
            <ul>
                <li>workflow:0:<strong>backlog</strong></li>
                <li>workflow:1:<strong>assigned</strong></li>
                <li>workflow:2:<strong>accepted</strong></li>
                <li>workflow:3:<strong>working</strong></li>
                <li>workflow:4:<strong>fixed</strong></li>
            </ul>
            <p>In this example, the whole labels are visible on github, but only the emphased part will be visible here.</p>
            <p>And the number is used for ordering.</p>
            <p><strong>Is it useful ?</strong></p>
            <p>By grouping labels, you add some logic, and these groups are separated from the non-grouped labels in the search bar of the issues list.</p>
            <p>And you can use them to group the list of issues. With the previous example, you can filter issues and then group them by workflow.</p>
        </div>
    </div>
    <div class="span9">

    <div id="labels-editor-content">
        {% include "front/repository/dashboard/labels-editor/include-content.html" %}
    </div>

    <div id="label-type-edit-form" class="modal fancy hide fade" data-keyboard="false">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" title="Close" aria-hidden="true">&times;</button>
            <h6>Group editor</h6>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
            <div class="row-fluid auto-align">
                <div class="span6">
                    <button class="btn btn-default btn-loading" id="label-type-test-button" data-toggle="popover" data-placement="top" data-content="<i class='fa fa-spinner fa-spin'> </i> Loading..." data-title="Matching labels" >Test it ! <i class='fa fa-spinner fa-spin'> </i></button>
                    <button class="btn btn-blue submit btn-loading">Save the group <i class='fa fa-spinner fa-spin'> </i></button>
                </div>
                <div class="span6">
                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-red btn-loading delete" data-title="" data-content="<button class='btn btn-red confirm-deletion'>Confirm deletion</button> <button class='btn btn-default cancel-deletion'>Cancel</button>" data-html="true" data-toggle="popover">Delete <i class='fa fa-spinner fa-spin'> </i></button>
                </div>
            </div>
        </div>
    </div>{# #label-type-edit-form #}

    <div id="label-edit-form" class="hide" data-edit-url="{{ base_label_edit_url }}" data-delete-url="{{ base_label_delete_url }}" data-create-url="{{ label_create_url }}">
        <form method="post" class="fill-up label-edit-form hide-order" data-id="%(id)s">
            {% csrf_token %}
            <input name='label_type' type='hidden' value="%(label_type_id)s" />
            <input name='order' type='text' value="%(order)s" placeholder="Order" title="Enter a number"/>
            <input name='name' type='text' value="%(name)s" placeholder="Name" />
            <input name='color' type='text' value="%(color)s" placeholder="Color" maxlength="6" title="Color"/>
            <div class="row-fluid auto-align">
                <div class="span4">
                    <button type='submit' class="btn btn-blue submit btn-loading">Save <i class='fa fa-spinner fa-spin'> </i></button>
                </div>
                <div class="span8">
                    <button type='button' class="btn btn-default cancel">Cancel</button>
                    <button type='button' class="btn btn-red delete btn-loading" data-title="" data-content="<button type='button' class='btn btn-red confirm-deletion'>Confirm deletion</button> <button type='button' class='btn btn-default cancel-deletion'>Cancel</button>" data-html="true" data-toggle="popover">Delete <i class='fa fa-spinner fa-spin'> </i></button>
                </div>
            </div>
        </form>
    </div>

    </div>

{% endblock dashboard-content %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static "front/js/select.2.js" %}" type="text/javascript"></script>
    <script src="{% static "front/js/spectrum.js" %}" type="text/javascript"></script>
    <script src="{% static "front/js/repository-labels-editor.js" %}" type="text/javascript"></script>

    <script type="text/javascript">
        $().ready(function() {
            LabelTypeForm.init();
        });
    </script>
{% endblock js_footer %}

gim/front/repository/dashboard/templates/front/repository/dashboard/labels-editor/form-errors.html
<div class="error">
    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
    {% for field in form %}
        {% if field.errors %}
            <label>{{ field.label }}:</label>
            {{ field.errors }}
        {% endif %}
    {% endfor %}
</div>

gim/front/repository/dashboard/templates/front/repository/dashboard/labels-editor/include-content.html
{% for label_type in label_types %}
    {% include label_type_include_template with label_type=label_type labels=label_type.visible_labels %}
{% endfor %}
{% include label_type_include_template with label_type=None labels=labels_without_type %}

gim/front/repository/dashboard/templates/front/repository/dashboard/labels-editor/label-type-edit.html
<form method="post" action="{% if form.instance.id %}{{ form.instance.get_edit_url }}{% else %}{{ label_type_create_url }}{% endif %}" method="post" class="fill-up{% if form.edit_mode.value %} mode{{ form.edit_mode.value }}{% endif %}" id="label-type-form" data-preview-url="{{ preview_url }}"{% if form.instance.id %} data-delete-url="{{ form.instance.get_delete_url }}"{% endif %}>

    {% csrf_token %}
    {{ form.non_field_errors }}

    <div>
        {{ form.name.label_tag }}
        {{ form.name.errors }}
        {{ form.name }}
    </div>

    <div>
        {{ form.edit_mode.label_tag }}
        {{ form.edit_mode.errors }}
        {{ form.edit_mode }}
        <div class="note">
            {{ form.edit_mode.help_text}}
        </div>
    </div>

    <div class="for-mode1">
        {{ form.regex.label_tag }}
        {{ form.regex.errors }}
        {{ form.regex }}
        <div class="note">
            {{ form.regex.help_text }}
        </div>
    </div>

    <div class="for-mode1">
        You can pick an example below:
        <div class="box label-type-samples" data-target="#id_regex">
            <div class="box-content">
                <ul class="box-list">
                    <li>
                        <a href="">
                            <strong>^Workflow - (?P&lt;order&gt;\d+) - (?P&lt;label&gt;.+)$</strong>
                            <div class="note">
                                Ex: "Workflow - 0 - <b>pending</b>", "Workflow - 1 - <b>assigned</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>^Type: (?P&lt;label&gt;.+)$</strong>
                            <div class="note">
                                Ex: "Type: <b>bug</b>", "Type: <b>enhancement</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>^\[component\] (?P&lt;label&gt;.+)$</strong>
                            <div class="note">
                                Ex: "[component] <b>search</b>", "[component] <b>contact-form</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>^Priority:(?P&lt;order&gt;\d+):(?P&lt;label&gt;.+)$</strong>
                            <div class="note">
                                Ex: "Priority:0:<b>low</b>", "Priority:1:<b>medium</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>^(?P&lt;order&gt;\d+) - (?P&lt;label&gt;.+)$</strong>
                            <div class="note">
                                Ex: "0 - <b>Backlog</b>", "1- <b>Assigned</b>"
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="for-mode2">
        {{ form.format_string.label_tag }}
        {{ form.format_string.errors }}
        {{ form.format_string }}
        <div class="note">
            {{ form.format_string.help_text|safe }}
        </div>
    </div>

    <div class="for-mode2">
        You can pick an example below:
        <div class="box label-type-samples" data-target="#id_format_string">
            <div class="box-content">
                <ul class="box-list">
                    <li>
                        <a href="">
                            <strong>Workflow - {order} - {label}</strong>
                            <div class="note">
                                Ex: "Workflow - 0 - <b>pending</b>", "Workflow - 1 - <b>assigned</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>Type: {label}</strong>
                            <div class="note">
                                Ex: "Type: <b>bug</b>", "Type: <b>enhancement</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>[component] {label}</strong>
                            <div class="note">
                                Ex: "[component] <b>search</b>", "[component] <b>contact-form</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>Prioriy:{order}:{label}</strong>
                            <div class="note">
                                Ex: "priority:0:<b>low</b>", "priority:1:<b>medium</b>"
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <strong>{order} - {label}</strong>
                            <div class="note">
                                Ex: "0 - <b>Backlog</b>", "1- <b>Assigned</b>"
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="for-mode3">
        {{ form.labels_list.label_tag }}
        {{ form.labels_list.errors }}
        {{ form.labels_list }}
        <div class="note">
            {{ form.labels_list.help_text }}
        </div>
    </div>


    <input type='submit' name='submit' value='Save changes' />
</form>
<script type="text/javascript">
    LabelTypeForm.update();
</script>

gim/front/repository/dashboard/templates/front/repository/dashboard/labels-editor/label-type-preview.html
{% if error %}
    <div class="alert alert-error">
        There is a problem with your configuration
    </div>

    {% include "front/repository/dashboard/labels-editor/form-errors.html" %}

{% else %}
    {% if matching_labels %}
        <ul class="unstyled labels">
            {% for label in matching_labels %}
                <li title="{{ label.name }}" style="border-bottom-color: #{{ label.color }};">{{ label.typed_name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="alert">
            No matching labels !
        </div>
    {% endif %}
{% endif %}