gim/front/activity/urls.py
activity_pattern = r'^activity/$'

gim/front/auth/urls.py
from django.conf.urls import patterns, url

from .views import LoginView, ConfirmView, LogoutView

urlpatterns = patterns('',
    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^confirm/$', ConfirmView.as_view(), name='confirm'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
)

gim/front/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

from gim.front.views import HomeView

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^auth/', include('gim.front.auth.urls', namespace='auth')),
    url(r'^dashboard/', decorator_include(login_required, 'gim.front.dashboard.urls', namespace='dashboard')),
    url(r'^(?P<owner_username>[^/]+)/(?P<repository_name>[^/]+)/', decorator_include(login_required, 'gim.front.repository.urls', namespace='repository'))
)

gim/graphs/urls.py
from django.conf.urls import patterns, url

from .views import IssuesByDayForRepo

urlpatterns = patterns('',
    url(r'^issues-by-day/(?P<repository_id>\d+)/', IssuesByDayForRepo.as_view(), name='issues_by_day_for_repo'),
)

gim/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('gim.front.urls', namespace='front', app_name='front')),

    url(r'^core-admin/', include(admin.site.urls)),
    url(r'^hooks/', include('gim.hooks.urls', namespace='hooks')),
    url(r'^graphs/', include('gim.graphs.urls', namespace='graphs')),
    url(r'^', include('gim.front.urls', namespace='front', app_name='front')),
)

gim/front/activity/views.py
import re


class ActivityViewMixin(object):
    RE_VALIDATE_SCORE = re.compile(r'^\d{14}\.\d+$')
    partial_template_name = 'front/activity/include_activity.html'

    @classmethod
    def _validate_score(cls, score):
        if score and cls.RE_VALIDATE_SCORE.match(score):
            return score
        return None

    @property
    def activity_args(self):
        if not hasattr(self, '_activity_args'):
            min = self._validate_score(self.request.GET.get('min'))
            max = self._validate_score(self.request.GET.get('max'))
            self._activity_args = {
                'min': min,
                'max': max,
                'withscores': True
            }
        return self._activity_args

    def get_context_data(self, *args, **kwargs):
        context = super(ActivityViewMixin, self).get_context_data(**kwargs)
        context['activity_args'] = self.activity_args
        context['partial_activity'] = bool(self.request.GET.get('partial'))
        return context

    def get_template_names(self):
        if self.request.GET.get('partial'):
            return self.partial_template_name
        return super(ActivityViewMixin, self).get_template_names()

gim/front/dashboard/repositories/views.py
from collections import namedtuple
from itertools import groupby

from django.views.generic import FormView, TemplateView, RedirectView
from django.shortcuts import redirect
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy

from limpyd_jobs import STATUSES

from gim.core.models import Repository, GithubUser, AVAILABLE_PERMISSIONS
from gim.subscriptions.models import (WaitingSubscription,
                                      WAITING_SUBSCRIPTION_STATES,
                                      SUBSCRIPTION_STATES, )

from gim.core import GITHUB_HOST
from gim.core.tasks.repository import FirstFetch
from gim.hooks.tasks import CheckRepositoryEvents

from gim.front.mixins.views import LinkedToUserFormViewMixin, DeferrableViewPart

from .forms import AddRepositoryForm, RemoveRepositoryForm


FakeUser = namedtuple('FakeUser', ['username'])
FakeRepository = namedtuple('FakeRepository', ['owner', 'name', 'full_name', 'no_infos', 'github_url'])


NO_REPOSITORY = '_/_'


class ToggleRepositoryBaseView(LinkedToUserFormViewMixin, FormView):
    """
    Base view to use to add/remove a repository
    """

    success_url = reverse_lazy('front:dashboard:repositories:choose')
    ajax_success_url = reverse_lazy('front:dashboard:repositories:ajax-repo')
    http_method_names = [u'post']

    def __init__(self, *args, **kwargs):
        self.repo_full_name = None
        super(ToggleRepositoryBaseView, self).__init__(*args, **kwargs)

    def form_invalid(self, form):
        """
        If the form is invalid, return to the list of repositories the user
        can add, with an error message
        """
        if 'name' in form._errors:
            self.repo_full_name = NO_REPOSITORY
        else:
            self.repo_full_name = form.repo_full_name
        messages.error(self.request, form.get_main_error_message())
        return redirect(self.get_success_url())

    def get_success_url(self):
        """
        IF we are in ajax mode, redirect to the ajax view of the current repo
        """
        if self.request.is_ajax() and self.repo_full_name:
            return reverse_lazy('front:dashboard:repositories:ajax-repo',
                                kwargs={'name': self.repo_full_name})

        return super(ToggleRepositoryBaseView, self).get_success_url()


class AddRepositoryView(ToggleRepositoryBaseView):
    form_class = AddRepositoryForm

    def form_valid(self, form):
        name = self.repo_full_name = form.cleaned_data['name']

        # create the waiting subscription if not exists
        subscription, created = WaitingSubscription.objects.get_or_create(
            user=self.request.user,
            repository_name=name
        )

        if not created:
            # the subscription already exists, force the state and updated_at
            subscription.state = WAITING_SUBSCRIPTION_STATES.WAITING
            subscription.save()

        message = 'Your subscription to <strong>%s</strong> will be added shortly'
        # if the repository exists (and fetched), convert into a real subscription
        try:
            repository = subscription.repository
            if not repository.first_fetch_done:
                raise Repository.DoesNotExist()
        except Repository.DoesNotExist:
            # add a job to fetch the repository
            FirstFetch.add_job(name, gh=self.request.user.get_connection())
        else:
            # If a FirstFetch is still running, do nothing more, but else...
            if repository.first_fetch_done:
                message = 'Your subscription to <strong>%s</strong> was just added'
                subscription.convert(form.can_use)
                # start fetching events (it'll be ignored if there is already a queued job)
                CheckRepositoryEvents.add_job(repository.id)

        messages.success(self.request, message % name)

        return super(AddRepositoryView, self).form_valid(form)


class RemoveRepositoryView(ToggleRepositoryBaseView):
    form_class = RemoveRepositoryForm

    def form_valid(self, form):
        name = self.repo_full_name = form.cleaned_data['name']

        form.subscription.delete()

        messages.success(self.request, 'Your subscription to <strong>%s</strong> was just removed' % name)

        return super(RemoveRepositoryView, self).form_valid(form)


class WithRepoMixin(object):

    @property
    def available_repositories(self):
        """
        Return a dict with, for each available repository for the user, the
        repository fullname as key and the "AvailableRepository" object as value
        """
        if not hasattr(self, '_available_repositories'):
            self._available_repositories = {
                ar.repository.full_name: ar
                for ar in self.request.user.available_repositories_set.all()
                                           .prefetch_related('repository__owner')
            }
        return self._available_repositories

    @property
    def subscribed_repositories(self):
        """
        Return a dict with, for each available repository for the user, the
        repository fullname as key and the "Subscription" object as value
        """
        if not hasattr(self, '_subscribed_repositories'):
            self._subscribed_repositories = {
                s.repository.full_name: s
                for s in self.request.user.subscriptions.all()
                              .prefetch_related('repository__owner')
            }
        return self._subscribed_repositories

    @property
    def waiting_subscriptions(self):
        """
        Return a dict with, for each "waiting subscriptions" of the user, the
        repository fullname as key, and the "WaitingSubscription" object as value
        """
        if not hasattr(self, '_waiting_subscriptions'):
            self._waiting_subscriptions = {
                s.repository_name: s
                for s in self.request.user.waiting_subscriptions.all()
            }

        return self._waiting_subscriptions

    @property
    def organizations(self):
        """
        Return the organizations the user belongs to
        """
        if not hasattr(self, '_organizations'):
            self._organizations = list(self.request.user.organizations.all())
        return self._organizations

    def get_organization_by_name(self, name):
        """
        Try to return an organization a user belongs to based on its name
        """
        try:
            return [o for o in self.organizations if o.username == name][0]
        except IndexError:
            return None

    def get_repository_from_full_name(self, full_name):
        """
        Return a "FakeRepository" object based on the repository's full name
        given as parameter. It contains enough data to act as a real
        repository in templates.
        If the owner of the repository doesn't exist, it will be a "FakeUser"
        """
        owner_username, repository_name = full_name.split('/')
        try:
            owner = GithubUser.objects.get(username=owner_username)
        except GithubUser.DoesNotExist:
            owner = FakeUser(
                username=owner_username,
            )
        return FakeRepository(
            name=repository_name,
            full_name=full_name,
            owner=owner,
            no_infos=True,
            github_url=GITHUB_HOST + full_name
        )

    def get_organization_and_org_name_from_name(self, name):
        """
        Based on a repository name, return:
        - the organization if there is one in ones the user belongs to
        - the organnization name, or __others__, or None
        """
        org_name = None
        org = self.get_organization_by_name(name)
        if org:
            org_name = org.username
        elif name != self.request.user.username:
            org_name = '__others__'

        return org, org_name

    def get_context_data(self, **kwargs):
        context = super(WithRepoMixin, self).get_context_data(**kwargs)

        context.update({
            'available_repositories': self.available_repositories,
            'subscribed_repositories': self.subscribed_repositories,
            'waiting_subscriptions': self.waiting_subscriptions,
            'SUBSCRIPTION_STATES': SUBSCRIPTION_STATES,
            'WAITING_SUBSCRIPTION_STATES': WAITING_SUBSCRIPTION_STATES,
            'AVAILABLE_PERMISSIONS': AVAILABLE_PERMISSIONS,
        })

        return context


class ShowRepositoryAjaxView(WithRepoMixin, TemplateView):
    template_name = 'front/dashboard/repositories/ajax_repo.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ShowRepositoryAjaxView, self).get_context_data(*args, **kwargs)

        user = self.request.user

        full_name = self.kwargs['name']

        if full_name == NO_REPOSITORY:
            return context

        owner_name, repo_name = full_name.split('/')

        in_tabs = []

        # which org ?
        org, org_name = self.get_organization_and_org_name_from_name(owner_name)

        # get repository, and tabs o insert it
        try:
            repository = Repository.objects.get(
                            owner__username=owner_name,
                            name=repo_name
                        )
        except:
            # the repository doesn't exists yet
            repository = self.get_repository_from_full_name(full_name)

            # it is in the waiting list ?
            if user.waiting_subscriptions.filter(repository_name=full_name).exists():
                in_tabs.append('subscriptions')

        else:
            # we have the repository ok, check what this repo is for the user

            if user.available_repositories.filter(id=repository.id).exists():
                if org:
                    in_tabs.append('available_in_orgs')
                else:
                    in_tabs.append('available_not_in_orgs')

gim/front/dashboard/views.py
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy

from gim.activity.limpyd_models import RepositoryActivity

from gim.front.mixins.views import WithSubscribedRepositoriesViewMixin, DeferrableViewPart
from gim.front.activity.views import ActivityViewMixin


class DashboardActivityPart(ActivityViewMixin, DeferrableViewPart, WithSubscribedRepositoriesViewMixin, TemplateView):
    part_url = reverse_lazy('front:dashboard:activity')
    template_name = 'front//dashboard/include_activity.html'
    deferred_template_name = 'front/dashboard/include_activity_deferred.html'

    repository_pks = None

    def inherit_from_view(self, view):
        super(DashboardActivityPart, self).inherit_from_view(view)
        self.repository_pks = view.repository_pks

    def get_pks(self):
        return [s.repository_id for s in self.subscriptions]

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardActivityPart, self).get_context_data(**kwargs)

        activity, has_more = RepositoryActivity.get_for_repositories(
                                    pks=self.repository_pks or self.get_pks(),
                                    **self.activity_args
                                )
        context.update({
            'activity': RepositoryActivity.load_objects(activity),
            'more_activity': has_more,
            'activity_mode': 'repositories',
        })

        return context


class DashboardHome(WithSubscribedRepositoriesViewMixin, TemplateView):
    template_name = 'front/dashboard/home.html'
    url_name = 'front:dashboard:home'

    def get_context_data(self, **kwargs):
        context = super(DashboardHome, self).get_context_data(**kwargs)

        repositories = context['subscribed_repositories']
        subscription_by_repo_id = dict((s.repository_id, s) for s in self.subscriptions)

        for repository in repositories:
            repository.user_counts_open = repository.counters.get_user_counts(self.request.user.pk)

        context['subscription_by_repo_id'] = subscription_by_repo_id

        self.repository_pks = subscription_by_repo_id.keys()
        context['parts'] = {
            'activity': DashboardActivityPart().get_as_deferred(self),
        }

        return context

gim/front/repository/board/views.py
from gim.front.repository.views import BaseRepositoryView


class BoardView(BaseRepositoryView):
    name = 'Board'
    url_name = 'board'
    template_name = 'front/repository/board/base.html'

gim/front/repository/views.py
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import classonlymethod
from django.views.generic import DetailView

from gim.front.mixins.views import SubscribedRepositoryViewMixin, WithSubscribedRepositoriesViewMixin


class BaseRepositoryView(WithSubscribedRepositoriesViewMixin, SubscribedRepositoryViewMixin, DetailView):
    # details vue attributes
    template_name = 'front/repository/base.html'

    # specific attributes to define in subclasses
    name = None
    url_name = None
    default_qs = None

    # set to False to not display in the main menu bar
    display_in_menu = True

    # internal attributes
    main_views = []

    @classonlymethod
    def as_view(cls, *args, **kwargs):
        """
        Override to call register_main_view if the view is a main one
        """
        if BaseRepositoryView in cls.__bases__:
            BaseRepositoryView.register_main_view(cls)
        return super(BaseRepositoryView, cls).as_view(*args, **kwargs)

    @classonlymethod
    def register_main_view(cls, view_class):
        """
        Store views to display as main views
        """
        if view_class not in BaseRepositoryView.main_views:
            view_class.main_url_name = view_class.url_name
            BaseRepositoryView.main_views.append(view_class)

    def get_context_data(self, **kwargs):
        """
        Set default content for the repository views:
            - list of available repositories
            - list of all main views for this repository
        """
        context = super(BaseRepositoryView, self).get_context_data(**kwargs)

        # we need a list of all main views for this repository
        repo_main_views = []
        reverse_kwargs = self.repository.get_reverse_kwargs()
        for view_class in BaseRepositoryView.main_views:
            main_view = {
                'url_name': view_class.url_name,
                'display_in_menu': view_class.display_in_menu,
                'url': reverse_lazy('front:repository:%s' % view_class.url_name, kwargs=reverse_kwargs),
                'qs': view_class.default_qs,
                'is_current': self.main_url_name == view_class.url_name,
                'title': view_class.name
            }
            repo_main_views.append(main_view)

        context['repository_main_views'] = repo_main_views

        return context

gim/front/dashboard/templates/front/dashboard/base.html
{% extends "front/base.html" %}

{% block body_classes %}dashboard{% endblock %}
{% block title %}Your dashboard{% endblock title %}

{% block header_nav %}
    <ul class="nav">
        <li{% if view.url_name == "front:dashboard:home" %} class="active"{% endif %}>
            <a role="menuitem" href="{% url "front:dashboard:home" %}">
                <i class="fa fa-tachometer"> </i>
                Dashboard
            </a>
        </li>
        <li{% if view.url_name == "front:dashboard:repositories:choose" %} class="active"{% endif %}>
            <a role="menuitem" href="{% url "front:dashboard:repositories:choose" %}">
                <i class="fa fa-check-circle"> </i>
                Subscriptions
            </a>
        </li>

    </ul>
{% endblock header_nav %}


{% block main %}
    <div class="row-fluid row-header">
        <div class="span12">
            <div class="area-top">
                {% block dashboard-header %}{% endblock %}
            </div>
        </div>
    </div>
    {% block dashboard-main %}{% endblock %}
{% endblock main %}

gim/front/dashboard/templates/front/dashboard/home.html
{% extends "front/dashboard/base.html" %}
{% load staticfiles frontutils repository_tags issues_tags %}
{% static 'front/img/default-avatar.png' as default_avatar %}

{% block body_id %}dashboard_home{% endblock %}
{% block body_classes %}{{block.super}} dashboard-2cols{% endblock %}
{% block extra_css %}
    <link href="{% static "front/css/pages/dashboard/dashboard-home.css" %}" rel="stylesheet">
{% endblock extra_css %}

{% block dashboard-header %}
    <div class="header">
        <h3><i class="fa fa-tachometer"> </i> Your dashboard</h3>
    </div>
{% endblock dashboard-header %}

{% block dashboard-main %}

    <div class="row-fluid">{% spaceless %}
        <div class="span6 dashboard-col">
            <div class="box col-part full-col" id="subscribed_repositories">
                <div class="box-header">
                    <span class="title">Subscribed repositories</span>
                    {% if subscribed_repositories|length %}
                        <ul class="unstyled box-toolbar">
                            <li>
                                {% include "front/include_quicksearch.html" with target="#subscribed_repositories .box-section" content=".news-title" class="small" only %}
                            </li>
                        </ul>
                    {% endif %}
                </div>{# .box-header #}
                <div class="box-content">
                    {% if subscribed_repositories|length %}
                        {% for repository in subscribed_repositories %}
                        {% with assigned_url=repository|base_url_issues_filtered_by_assigned:user createdy_url=repository|base_url_issues_filtered_by_created_by:user issues_url=repository|repository_view_url:'issues' global_counts=repository.counters.get_global_counts %}

                            <div class="box-section news" data-repo-id="{{ repository.id }}">
                                <div class="avatar"><img class="avatar-small img-circle" src="{{ repository.owner.avatar_url|default:default_avatar }}" /></div>
                                <ul class="unstyled counters">
                                    {% with count=repository.user_counts_open.assigned.total class="user-assigned" title="All open issues assigned to you (including pull requests)" %}
                                        {% if count or count == 0 %}
                                        <li class="{{ class }} {% if count > 10 %}high{% elif count > 5 %}medium{% elif count %}low{% else %}none{% endif %}" title="{{ title }}">
                                           <a href="{{ assigned_url }}?state=open">{{ count }}</a>
                                        </li>
                                        {% else %}
                                        <li class="not-collab" title="You're not a collaborator on this repository, you cannot be assigned to issues">-</li>
                                        {% endif %}
                                    {% endwith %}
                                    {% with count=repository.user_counts_open.created.total class="user-created" title="All open issues created by you (including pull requests)" %}
                                        <li class="{{ class }} {% if count > 10 %}high{% elif count > 5 %}medium{% elif count %}low{% else %}none{% endif %}" title="{{ title }}">
                                            <a href="{{ createdy_url }}?state=open">{{ count }}</a>
                                        </li>
                                    {% endwith %}
                                    {% comment %}
                                    {% with count=repository.user_counts_open.created.prs class="user-assigned" title="All open pull requests created by you" %}
                                        <li class="{{ class }} {% if count > 10 %}high{% elif count > 5 %}medium{% elif count %}low{% else %}none{% endif %}" title="{{ title }}">
                                            <a href="{{ createdy_url }}?state=open&amp;pr=yes">{{ count }}</a>
                                        </li>
                                    {% endwith %}
                                    {% endcomment %}
                                    {% with count=global_counts.open.prs class="all-prs" title="All open pull requests" %}
                                        <li class="{{ class }} {% if count > 10 %}high{% elif count > 5 %}medium{% elif count %}low{% else %}none{% endif %}" title="{{ title }}">
                                            <a href="{{ issues_url }}?state=open&amp;pr=yes">{{ count }}</a>
                                        </li>
                                    {% endwith %}
                                    {% with count=global_counts.open.total class="all" title="All open issues (including pull requests)" %}
                                        <li class="{{ class }} {% if count > 10 %}high{% elif count > 5 %}medium{% elif count %}low{% else %}none{% endif %}" title="{{ title }}">
                                            <a href="{{ issues_url }}?state=open">{{ count }}</a>
                                        </li>
                                    {% endwith %}
                                </ul>
                                  <div class="news-content">
                                    <div class="news-title">
                                        <a href="{{ repository.get_absolute_url }}" title="View the repository '{{ repository }}'">{{ repository.owner.username }}/<wbr />{{ repository.name }}</a>
                                    </div>
                                </div>
                            </div>

                        {% endwith %}
                        {% endfor %}
                    {% else %}
                        <div class="empty-area">
                            <p>You didn't subscribe to any repositories !</p>
                            <p><a href="{% url "front:dashboard:repositories:choose" %}">Go to your subscriptions page !</a>
                        </div>
                    {% endif %}
                </div>{# .box-content #}
            </div>{# #subscribed_repositories.box #}
        </div>{# .span6 #}

        <div class="span6 dashboard-col">
            {{ parts.activity|safe }}
        </div>{# .span6 #}
    {% endspaceless %}</div>{# .row-fluid #}
{% endblock dashboard-main %}d

{% block js_footer %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "graphs/js/jquery.sparkline.min.js" %}" ></script>
    <script type="text/javascript" src="{% static "graphs/js/graphs.js" %}" ></script>
    <script type="text/javascript">
        var graph_data_urls = graph_data_urls || {};
        graph_data_urls.issues_by_day = "{% url 'graphs:issues_by_day_for_repo' repository_id=99999 %}";
        var get_graph = function () {
            var $repo_node = $('#subscribed_repositories .box-section[data-repo-id]:not(.has-graph):not(.hidden)').first();
            if (!$repo_node.length) {
                $repo_node = $('#subscribed_repositories .box-section[data-repo-id]:not(.has-graph)').first();
            }
            if ($repo_node.length) {
                IssuesByDayGraph.fetch_and_make_graph($repo_node.data('repo-id'), 40, $repo_node.children('.news-content'), function() {
                    $repo_node.addClass('has-graph');
                    get_graph();
                });
            }
        };
        $().ready(function() {
            get_graph();
        });
    </script>
{% endblock js_footer %}

{% block modal-windows %}
    {{ block.super }}
    {% include "front/modal_issue_view.html" %}
{% endblock modal-windows %}

gim/front/dashboard/templates/front/dashboard/include_activity.html
<div class="box deferrable col-part full-col activity-feed for-{{ activity_mode }}" id="main_activity" data-url="{{ defer_url }}" data-mode='{{ activity_mode }}'>
    <div class="box-header">
        <span class="title">Last activity</span>
        {% include "front/activity/include_toolbar.html" %}
    </div>
    <div class="box-content">
        {% if activity|length %}
            {% include "front/activity/include_activity.html" %}
        {% else %}
            <div class="empty-area">It seems that there is no activity at all!</div>
        {% endif %}
    </div>{# .box-content #}
    {% if not partial_activity %}
        <script type="text/javascript">
            Activity.delay_check_new_activity('#main_activity');
        </script>
    {% endif %}
</div>{# #main_activity.box #}

gim/front/dashboard/templates/front/dashboard/include_activity_deferred.html
{% extends "front/base_deferred_block.html" %}

{% block deferred-classes %}box col-part full-col activity-feed{% endblock %}
{% block deferred-id %}main_activity{% endblock %}

{% block deferred-placeholder %}
    <div class="box-header">
        <span class="title">Last activity</span>
    </div>
    <div class="box-content">
        {{ block.super }}
    </div>
{% endblock %}